name: Deployment Workflow
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install frontend dependencies
        run: npm install
      - name: build frontend asset 
        run: npm run build
      - name: Install dotenv  
        run: |
          curl -o dotenv https://raw.githubusercontent.com/bashup/dotenv/master/dotenv
          chmod +x dotenv 
      - name: Create .env file and set values
        run: |
          cp .env.example .env  
          ./dotenv -f .env set \
            APP_NAME='"Laravel POS"' \
            APP_ENV=production \
            APP_DEBUG=false \
            APP_URL=http://laravelpos-env-1.eba-kpfhmwyf.ap-southeast-1.elasticbeanstalk.com \
      - name: Generate app key 
        run: php artisan key:generate
      - name: Create zip deployment package
        run: zip -r deploy.zip ./ -x "dotenv"
      - name: Deploy to elastic beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "laravel POS"
          environment_name: "LaravelPOS-env-1"
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-476139910356
          version_label: laravel-pos-${{ github.run_number }}
          region: ap-southeast-1
          deployment_package: deploy.zip